#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

[ -f $HOME/.profile ] && source $HOME/.profile

# Preserve macOS alt & cmd cursor movement
# https://github.com/ghostty-org/ghostty/discussions/2363#discussioncomment-11051274
bindkey "\e[1;3D" backward-word     # ⌥←
bindkey "\e[1;3C" forward-word      # ⌥→
bindkey "^[[1;9D" beginning-of-line # cmd+←
bindkey "^[[1;9C" end-of-line       # cmd+→

# Setup git autocomplete
fpath=(~/.zsh $fpath)
zstyle ':completion:*:*:git:*' script ~/git-completion.bash


# # Homebrew: get autocompletions into zsh
# # https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
# if type brew &>/dev/null; then
#   FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

#   autoload -Uz compinit
#   compinit
# fi


# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

source ~/bin/dotfiles/bash/aliases
source ~/bin/dotfiles/bash/env
source ~/bin/dotfiles/bash/config
if [ -d ~/bin/dotfiles/private/ ]; then
  for f in ~/bin/dotfiles/private/*; do source $f; done
fi

# unalias git
# This is needed for hub/git autocompletion
setopt complete_aliases

DEFAULT_USER="banderson"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

[ -f ~/bin/google-cloud-sdk/completion.zsh.inc ] && source ~/bin/google-cloud-sdk/completion.zsh.inc

[ -f ~/bin/google-cloud-sdk/path.zsh.inc ] && source ~/bin/google-cloud-sdk/path.zsh.inc


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Use ag instead of the default find command for listing candidates.
# - The first argument to the function is the base path to start traversal
# - Note that ag only lists files not directories
# - See the source code (completion.{bash,zsh}) for the details.
_fzf_compgen_path() {
  ag -g "" "$1"
}

[ -f ~/.iterm2_shell_integration.zsh ] && source ~/.iterm2_shell_integration.zsh

[ -f ~/bin/aws_zsh_completer.sh ] && source ~/bin/aws_zsh_completer.sh

if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  source ~/.config/exercism/exercism_completion.zsh
fi
export PATH="/usr/local/opt/openssl/bin:$PATH"

export DENO_DIR=$HOME/.deno

# Add custom functions to ~/.zfunc
fpath=( ~/.zfunc "${fpath[@]}" )

fpath=(~/.zsh $fpath)
autoload -Uz compinit
compinit -u


[ -f ~/.zprezto-contrib/fzf-tab/fzf-tab.plugin.zsh ] && source ~/.zprezto-contrib/fzf-tab/fzf-tab.plugin.zsh

eval "$(_SQLITE_UTILS_COMPLETE=zsh_source sqlite-utils)"

# =============================================================

# Added by nex: https://git.hubteam.com/HubSpot/nex
. ~/.hubspot/shellrc
